### ISSUE TITLE
ddollar/heroku-accounts auto-uninstalled, and didn't provide alternative

### ISSUE THREAD

**Issue by nzifnab** [heroku/heroku-accounts#2]
$ heroku accounts
    Uninstalling deprecated ddollar/heroku-accounts plugin... done
    * work
    work-admin
    $ heroku accounts
     !    `accounts` is not a heroku command.
     !    See `heroku help` for a list of available commands.

Um... that seems overly-aggressive. Couldn't it at least say something like "install the official plugin using `command`" or... something?

Also, `-r production` is no longer working for me when attempting to run heroku commands. I get this:

    $ cat .git/config
    [remote "production"]
	    url = git@heroku.work:my-cool-app.git
	    fetch = +refs/heads/*:refs/remotes/production/*
    $ heroku run rails c -r production
     ▸    could not find app name in production git remote

This is a heroku-accounts issue, because if I change the gitconfig remote to look at `git@heroku.com`, the `-r` option works just fine, but when i use `heroku accounts:set work` it changes it back to `git@heroku.work`.

Why can't I just... keep using the old *working* version of the plugin?  :(

**Comment by dickeyxxx** [comment]
The old plugin won't work because we're replacing the entire toolbelt and with the new one we will no longer support the monkey-patching functionality that the other plugin depends on to function. Also, we've moved away from using ssh to connect for `git push` which that plugin depends on. It will no longer work with `heroku run` at all.

A deprecation warning has been up for months, but at this point enough of the commands no longer function we decided to fully deprecate the old plugin.

The issue with `-r` you're experiencing isn't from this version of the plugin, it's from the other one. If you use `heroku git:remote` it will fix your remotes to what they should be.

**Comment by nzifnab** [comment]
> A deprecation warning has been up for months, but at this point enough of the commands no longer function we decided to fully deprecate the old plugin.

That deprecation warning started showing up for everyone in my team only last week...

Thanks for the note on `heroku git:remote`, with the official plugin & resetting my remote w/ that, it seems to be functioning as expected.

**Comment by cjolly** [comment]
@dickeyxxx thanks for this explanation - where should we be keeping an eye out for these deprecation messages in the future? I follow heroku changelog on twitter and didn't see anything here. I only saw the deprecation start last week around when this issue cropped up: https://github.com/ddollar/heroku-accounts/issues/85

**Comment by dickeyxxx** [comment]
well there were 2 levels of deprecation, one only happened when you ran `heroku login`, that one has been in for a long time, but last week we made the warning much more apparent, but because it was also incompatible with more commands (most importantly, run) we decided to be a bit more forceful due to support tickets where people weren't able to get run to work with having the plugin installed
