### ISSUE TITLE
Login failures with PGbackups

### ISSUE THREAD

**Issue by rstammer** [heroku/heroku-accounts#3]
I'm usually following [the heroku instructions on PGBackups](https://devcenter.heroku.com/articles/heroku-postgres-backups) when trying to download a database dump of my application:

```
curl -o latest.dump `heroku pg:backups public-url -r my_remote --account my_account` 
```

Even if I have set the account having access to the repository via

```
heroku accounts:set my_account
```

the CLI will ask me for my credentials instead of using my SSH key.
This would not be really problematic, but the CLI gets stuck. It confirms the correctness of the credentials but starts asking again iteratively:

![bildschirmfoto 2016-10-05 um 10 40 58](https://cloud.githubusercontent.com/assets/3685123/19106669/e3068c92-8ae8-11e6-83f0-14bd33ed69b4.png)
## 

Version information:
![bildschirmfoto 2016-10-05 um 10 48 42](https://cloud.githubusercontent.com/assets/3685123/19106745/57c2af3e-8ae9-11e6-88bc-21fa09d3cce2.png)

**Comment by ransombriggs** [comment]
@neumanrq I do not think that the `pg:backups` command takes an `--account` flag, it should use the credentials stored in your `~/.netrc` file like the rest of the heroku commands to authenticate.  What happens when you try running it without?

```
curl -o latest.dump `heroku pg:backups public-url -r my_remote` 
```

As for the iterative authentication prompts, I see that you have `heroku-accounts` listed twic in your version, could you uninstall the heroku-accounts plugin and verify that both copies are removed and then try installing again?

```
heroku plugins:uninstall heroku-accounts
```

**Comment by rstammer** [comment]
I'm sorry - my bad. I only tried removing the plugin _once_, but then the "wrong one" survived. I was not aware it was installed multiple times. Running the uninstall command you suggested _twice_ and reinstalling the plugin finally did the trick. 

Thanks for your help!
